apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kyverno
name: kyverno
repo: https://kyverno.github.io/kyverno/
version: v3.4.1
releaseName: kyverno
namespace: kyverno
valuesFile: values.yaml
